/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Models.*;
import Controller.*;
/**
 *
 * @author ADMIN
 */
public class FrameAnalytics extends javax.swing.JFrame {
    private String[] data;
    /**
     * Creates new form FrameAnalytics
     */
    public FrameAnalytics() {
        initComponents();
        this.data = ((People_QuanLy)services.user).loadAnalytics();
        songuoidung.setText(songuoidung.getText()+data[0]);
        sosach.setText(sosach.getText()+data[1]);
        sodanhmuc.setText(sodanhmuc.getText()+data[2]);
        sodanhgia.setText(sodanhgia.getText()+data[3]);
        sophienban.setText(sophienban.getText()+data[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        songuoidung = new javax.swing.JLabel();
        sosach = new javax.swing.JLabel();
        sodanhmuc = new javax.swing.JLabel();
        sodanhgia = new javax.swing.JLabel();
        sophienban = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thống kê người dùng");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Thống kê");

        songuoidung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        songuoidung.setText("Số người dùng  :");

        sosach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sosach.setText("Số sách hiện có : ");

        sodanhmuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sodanhmuc.setText("Danh mục sách : ");

        sodanhgia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sodanhgia.setText("Số lượt đánh giá : ");

        sophienban.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sophienban.setText("Phiên bản hệ thống : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(songuoidung)
                            .addComponent(sodanhmuc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sosach)
                                .addGap(232, 232, 232)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sodanhgia)
                                    .addComponent(sophienban)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addComponent(songuoidung)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(sosach))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(sodanhgia)
                        .addGap(30, 30, 30)
                        .addComponent(sophienban)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sodanhmuc)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAnalytics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel sodanhgia;
    private javax.swing.JLabel sodanhmuc;
    private javax.swing.JLabel songuoidung;
    private javax.swing.JLabel sophienban;
    private javax.swing.JLabel sosach;
    // End of variables declaration//GEN-END:variables
}
