/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.services;
import java.awt.BorderLayout;
import java.util.HashSet;
import java.awt.CardLayout;
import Models.Model_Sach;
import java.awt.Desktop;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JPanel;
import Models.*;
/**
 *
 * @author ADMIN
 */
public class FrameMainMenuStaff extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public FrameMainMenuStaff(JPanel panel) {    
        initComponents();
        if(panel == null){
            this.setContentPane(new PanelWelcome());
            this.validate();
            this.invalidate();
        }
        else
        {
            this.setContentPane(panel);
            this.validate();
            this.invalidate();
        }
        setAccess();
    }

    public void setAccess()
    {
        if(services.user instanceof People_QuanLy) //Manager
        {
            menuCart.setVisible(false);
            menuInventory.setVisible(false);
            menuSearchLogs.setVisible(false);
            menuHistoryBuyBook.setVisible(false);
        }
        if(services.user instanceof People_NhanVien) // Staff
        {
            menuAnalytics.setVisible(false);
            menuQuanLyNguoiDung.setVisible(false);
            menuLogs.setVisible(false);
            menuCart.setVisible(false);
            menuInventory.setVisible(false);
            menuHistoryBuyBook.setVisible(false);
        }
        if(services.user instanceof People_Khach) // Customer
        {
            menuQuanLy.setVisible(false);
            menuAnalytics.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        PanelChinh = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuQuanLy = new javax.swing.JMenu();
        menuQuanLyNguoiDung = new javax.swing.JMenuItem();
        menuQuanLySach = new javax.swing.JMenuItem();
        menuLogs = new javax.swing.JMenuItem();
        menuSearchLogs = new javax.swing.JMenuItem();
        menuCart = new javax.swing.JMenu();
        menuAnalytics = new javax.swing.JMenu();
        menuAccount = new javax.swing.JMenu();
        menuUserInfo = new javax.swing.JMenuItem();
        menuInventory = new javax.swing.JMenuItem();
        menuHistoryBuyBook = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuAuthor = new javax.swing.JMenu();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống hiệu sách");
        setName("PanelChinh"); // NOI18N
        setResizable(false);

        PanelChinh.setMinimumSize(new java.awt.Dimension(1420, 748));
        PanelChinh.setName("PanelChinh"); // NOI18N

        javax.swing.GroupLayout PanelChinhLayout = new javax.swing.GroupLayout(PanelChinh);
        PanelChinh.setLayout(PanelChinhLayout);
        PanelChinhLayout.setHorizontalGroup(
            PanelChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1567, Short.MAX_VALUE)
        );
        PanelChinhLayout.setVerticalGroup(
            PanelChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        menuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        menuHome.setText("Trang chủ");
        menuHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        menuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuHome);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/library.png"))); // NOI18N
        jMenu4.setText("Thư viện");
        jMenu4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        menuQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/manager.png"))); // NOI18N
        menuQuanLy.setText("Quản lý");
        menuQuanLy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuQuanLyMousePressed(evt);
            }
        });

        menuQuanLyNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/group-user.png"))); // NOI18N
        menuQuanLyNguoiDung.setText("Quản lý người dùng");
        menuQuanLyNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyNguoiDungMouseClicked(evt);
            }
        });
        menuQuanLyNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyNguoiDungActionPerformed(evt);
            }
        });
        menuQuanLy.add(menuQuanLyNguoiDung);

        menuQuanLySach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/books.png"))); // NOI18N
        menuQuanLySach.setText("Quản lý sách");
        menuQuanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLySachActionPerformed(evt);
            }
        });
        menuQuanLy.add(menuQuanLySach);

        menuLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logs.png"))); // NOI18N
        menuLogs.setText("Quản lý nhật ký");
        menuLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogsActionPerformed(evt);
            }
        });
        menuQuanLy.add(menuLogs);

        menuSearchLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/manage_logs.png"))); // NOI18N
        menuSearchLogs.setText("Tra cứu lịch sử");
        menuSearchLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSearchLogsMousePressed(evt);
            }
        });
        menuQuanLy.add(menuSearchLogs);

        jMenuBar1.add(menuQuanLy);

        menuCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cart.png"))); // NOI18N
        menuCart.setText("Giỏ hàng");
        menuCart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCartMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCart);

        menuAnalytics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/analytics.png"))); // NOI18N
        menuAnalytics.setText("Thống kê");
        menuAnalytics.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuAnalytics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuAnalyticsMousePressed(evt);
            }
        });
        jMenuBar1.add(menuAnalytics);

        menuAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_user.png"))); // NOI18N
        menuAccount.setText("Tài khoản");
        menuAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        menuUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user-menu.png"))); // NOI18N
        menuUserInfo.setText("Thông tin cá nhân");
        menuUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserInfoActionPerformed(evt);
            }
        });
        menuAccount.add(menuUserInfo);

        menuInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/inventory.png"))); // NOI18N
        menuInventory.setText("Kho sách của tôi");
        menuInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInventoryActionPerformed(evt);
            }
        });
        menuAccount.add(menuInventory);

        menuHistoryBuyBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/history.png"))); // NOI18N
        menuHistoryBuyBook.setText("Lịch sử mua hàng");
        menuHistoryBuyBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuHistoryBuyBookMousePressed(evt);
            }
        });
        menuAccount.add(menuHistoryBuyBook);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/change_pass.png"))); // NOI18N
        jMenuItem3.setText("Đổi mật khẩu");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuAccount.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        jMenuItem4.setText("Đăng xuất");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuAccount.add(jMenuItem4);

        jMenuBar1.add(menuAccount);

        menuAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/about_me.png"))); // NOI18N
        menuAuthor.setText("Nhóm tác giả");
        menuAuthor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAuthorMouseClicked(evt);
            }
        });
        menuAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAuthorActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuAuthor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelChinh.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuQuanLyNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyNguoiDungActionPerformed
        // TODO add your handling code here:
        //Quan ly nguoi dung
        this.setContentPane(new PanelManageAccount());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuQuanLyNguoiDungActionPerformed

    private void menuUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserInfoActionPerformed
        // TODO add your handling code here:
        //Thong tin ca nhan
        this.setContentPane(new PanelUserInfo());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuUserInfoActionPerformed

    private void menuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHomeActionPerformed

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        // TODO add your handling code here:
        this.setContentPane(new PanelWelcome());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuHomeMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //Change password
        this.setContentPane(new PanelChangePass());
        this.validate();
        this.invalidate();
        services.msg("Change pass clicked");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        //Dang xuat
        FrameLogin lg = new FrameLogin();
        lg.show();
        dispose();
        services.user.logout();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuQuanLyNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyNguoiDungMouseClicked
        // TODO add your handling code here:
        //Quan ly nguoi dung
        
    }//GEN-LAST:event_menuQuanLyNguoiDungMouseClicked

    private void menuQuanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLySachActionPerformed
        // TODO add your handling code here:
        this.setContentPane(new PanelManageBook());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuQuanLySachActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        this.setContentPane(new PanelLibrary());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void menuAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAuthorMouseClicked
        // TODO add your handling code here:
        try {
                boolean tmp = false;
                String author = "Trưởng nhóm : ";
                Statement stmt = services.cnn.con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM `author` WHERE 1 ORDER BY vaitro DESC");
                while(rs.next())
                {
                    if(!tmp) author += rs.getString("Ten");
                    tmp = true;
                    Desktop.getDesktop().browse(new URL(rs.getString("link_fb")).toURI());
                }
                services.msgbox("Author",author);
                    } 
            catch (Exception e) 
            {}
    }//GEN-LAST:event_menuAuthorMouseClicked

    private void menuLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogsActionPerformed
        // TODO add your handling code here:
        this.setContentPane(new PanelManageLogs());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuLogsActionPerformed

    private void menuCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCartMouseClicked
        // TODO add your handling code here:
        this.setContentPane(new PanelCart());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuCartMouseClicked

    private void menuInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInventoryActionPerformed
        // TODO add your handling code here:
        this.setContentPane(new PanelInventory());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuInventoryActionPerformed

    private void menuQuanLyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLyMousePressed

    private void menuSearchLogsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSearchLogsMousePressed
        // TODO add your handling code here:
        this.setContentPane(new PanelManageLogs());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuSearchLogsMousePressed

    private void menuHistoryBuyBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistoryBuyBookMousePressed

        this.setContentPane(new PanelManageLogs());
        this.validate();
        this.invalidate();
    }//GEN-LAST:event_menuHistoryBuyBookMousePressed

    private void menuAnalyticsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAnalyticsMousePressed
        // TODO add your handling code here:
        FrameAnalytics fr = new FrameAnalytics();
        fr.show();
    }//GEN-LAST:event_menuAnalyticsMousePressed

    private void menuAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAuthorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMainMenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMainMenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMainMenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMainMenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMainMenuStaff(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelChinh;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu menuAccount;
    private javax.swing.JMenu menuAnalytics;
    private javax.swing.JMenu menuAuthor;
    private javax.swing.JMenu menuCart;
    private javax.swing.JMenuItem menuHistoryBuyBook;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menuInventory;
    private javax.swing.JMenuItem menuLogs;
    private javax.swing.JMenu menuQuanLy;
    private javax.swing.JMenuItem menuQuanLyNguoiDung;
    private javax.swing.JMenuItem menuQuanLySach;
    private javax.swing.JMenuItem menuSearchLogs;
    private javax.swing.JMenuItem menuUserInfo;
    // End of variables declaration//GEN-END:variables
}
