/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Message;
import Controller.services;
import Models.Model_Sach;
import java.awt.Color;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.WIDTH;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class PanelManageBook extends javax.swing.JPanel {
    private DefaultTableModel model;
    private boolean isActiveImage = false;
    private String last_id = "-999";
    /**
     * Creates new form PanelManageBook
     */
    public PanelManageBook() {
        initComponents();
        this.model = (DefaultTableModel) tableListSach.getModel();
        try{
            String sqlTheLoai = "SELECT `ten` FROM `danhmuc` ";
            ResultSet rs = services.cnn.con.createStatement().executeQuery(sqlTheLoai);
            while(rs.next())
            {
                txtTheLoai.addItem(rs.getString("ten"));
            }
        }
        catch(Exception e)
        {
            services.msg(e);
        }
        this.loadListBook();
        this.loadBook(services.books.get(0).getID());
    }
    public void loadListBook()
    {
        this.model.setRowCount(0);
        try{
            String sqlGetListBook = "SELECT * FROM `khosach` ORDER BY book_id";
            String sqlGetTacGia = "SELECT * FROM `user` ORDER BY `user_id`";
            Statement stmt = services.cnn.con.createStatement();
            ResultSet rs = stmt.executeQuery(sqlGetListBook);
            while(rs.next())
            {   
                Model_Sach tmp = new Model_Sach(rs);
                this.model.addRow(new Object[]{tmp.getID(), tmp.getTen(), services.cnn.getRowInDB("danhmuc", "id", tmp.getTheLoai().trim()).getString("ten"), tmp.getSoLuong()});        
            }
            rs = stmt.executeQuery(sqlGetTacGia);
            while(rs.next())
            {
                txtTacGia.addItem(rs.getString("Ten"));
            }
        }
        catch(Exception e)
        {
            services.msgbox("Error", "Có lỗi trong quá trình lấy sách!");
            services.msg("PanelManageBook loadListBook(): "+e);
        }
    }

    public void loadBook(String id)
    {
        Model_Sach sach = services.getBookByID(id);
        if(sach==null)
        {
            return;
        }
        try{
            txtID.setText(sach.getID());
            txtTacGia.setSelectedItem(services.cnn.getRowInDB("user", "user_id", sach.getIdTacGia()).getString("Ten"));
            txtTen.setText(sach.getTen());
            txtTheLoai.setSelectedItem(services.cnn.getRowInDB("danhmuc", "id", sach.getTheLoai().trim()).getString("ten"));
            txtGia.setText(sach.getGia()+"");
            txtSL.setText(sach.getSoLuong()+"");
            txtImage.setText(sach.getImage());

            BufferedImage img = ImageIO.read(new URL(services.getUrlImageBook(sach.getImage())));
            ImageIcon icon = new ImageIcon(img.getScaledInstance(150, 200, WIDTH));
            imageBook.setIcon(icon);
        }
        catch(Exception e)
        {
            services.msgbox("Error","Không thể lấy thông tin sách");
            services.msg(e);
        }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JLabel();
        imageBook = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListSach = new javax.swing.JTable();
        txtSL = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        btnTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtImage = new javax.swing.JTextField();
        txtTinhTrang1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        txtTacGia = new javax.swing.JComboBox<>();
        txtTheLoai = new javax.swing.JComboBox<>();

        setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1420, 748));
        setPreferredSize(new java.awt.Dimension(1420, 748));

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tên");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tác giả");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thể loại");

        txtThanhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtThanhTien.setText("Giá");

        imageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/demo.jpg"))); // NOI18N
        imageBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTinhTrang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTinhTrang.setText("SL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Thông tin sách");

        txtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ID");

        tableListSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableListSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID sách", "Tên sách", "Thể loại", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableListSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListSachMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableListSachMousePressed(evt);
            }
        });
        tableListSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableListSachKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableListSachKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableListSach);

        txtSL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_test.png"))); // NOI18N
        btnTest.setBorderPainted(false);
        btnTest.setContentAreaFilled(false);
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("List sách hiện có");

        txtImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTinhTrang1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTinhTrang1.setText("Image");

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_update.png"))); // NOI18N
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_remove.png"))); // NOI18N
        btnRemove.setBorder(null);
        btnRemove.setBorderPainted(false);
        btnRemove.setContentAreaFilled(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_add-book.png"))); // NOI18N
        btnAddBook.setBorder(null);
        btnAddBook.setBorderPainted(false);
        btnAddBook.setContentAreaFilled(false);
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTheLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imageBook))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTinhTrang)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(txtThanhTien)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTinhTrang1)
                                .addGap(14, 14, 14)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSL)
                            .addComponent(txtID)
                            .addComponent(txtTen)
                            .addComponent(txtGia)
                            .addComponent(txtTacGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTheLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(689, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(569, 569, 569)
                .addComponent(btnAddBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtThanhTien)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTinhTrang)
                                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTinhTrang1)
                                    .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(btnRemove))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(imageBook)
                                .addGap(18, 18, 18)
                                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(btnAddBook)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        // TODO add your handling code here:
        try{
            String link = txtImage.getText();
            this.isActiveImage = services.setImgLabel(imageBook, services.getUrlImageBook(link), 150, 200);
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }//GEN-LAST:event_btnTestActionPerformed

    private void tableListSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListSachMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableListSachMouseClicked

    private void tableListSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableListSachKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableListSachKeyPressed

    private void tableListSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableListSachKeyReleased
        // TODO add your handling code here:
        int row = tableListSach.getSelectedRow();
        this.last_id = (String)tableListSach.getValueAt(row, 0);
        this.loadBook((String)tableListSach.getValueAt(row, 0));
    }//GEN-LAST:event_tableListSachKeyReleased

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:       
        services.disposeParent(this, new PanelAddBook());      
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(!services.setImgLabel(imageBook, services.getUrlImageBook(txtImage.getText()), 150, 200))
        {
            return;
        }
        try{
            Statement stmt = services.cnn.con.createStatement();
            String sqlUpdateBook = "UPDATE `khosach` SET `book_id`='"+txtID.getText()+"',`book_name`='"+txtTen.getText()+"',`tacgia`='"+services.cnn.getRowInDB("user", "Ten", (String)txtTacGia.getSelectedItem()).getString("user_id")+"',`theloai`='"+services.cnn.getRowInDB("danhmuc", "ten", (String)txtTheLoai.getSelectedItem()).getString("id")+"',"
                    + "`gia`='"+Integer.parseInt(txtGia.getText())+"',`soluong`='"+Integer.parseInt(txtSL.getText())+"',`image`='"+txtImage.getText()+"' WHERE book_id='"+this.last_id+"'";
            stmt.execute(sqlUpdateBook);
            services.msgbox("Success", "Cập nhật thông tin sách "+txtTen.getText()+" thành công!");
            services.sendLog(services.user.getID(),services.user.getTen(), "updatebook",Message.updateBook+this.last_id+", Ten : "+txtTen.getText());
        }catch(Exception e)
        {
            services.msg(e);
            services.msgbox("Error", "Không thể cập nhật sách");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        try{
            String logs = Message.deleteBook+this.last_id +", Ten : "+(String)services.cnn.getRowInDB("user", "user_id", last_id).getString("Ten");
            String sql = "DELETE FROM `khosach` WHERE book_id='"+this.last_id+"'";
            Statement stmt = services.cnn.con.createStatement();
            stmt.execute(sql);
            services.sendLog(services.user.getID(),"removebook",services.user.getTen(), logs);
            this.loadListBook();
            this.loadBook(services.books.get(0).getID());
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tableListSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListSachMousePressed
        // TODO add your handling code here:
        int row = tableListSach.getSelectedRow();
        this.last_id = (String)tableListSach.getValueAt(row, 0);
        this.loadBook((String)tableListSach.getValueAt(row, 0));
    }//GEN-LAST:event_tableListSachMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel imageBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListSach;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtImage;
    private javax.swing.JTextField txtSL;
    private javax.swing.JComboBox<String> txtTacGia;
    private javax.swing.JTextField txtTen;
    private javax.swing.JLabel txtThanhTien;
    private javax.swing.JComboBox<String> txtTheLoai;
    private javax.swing.JLabel txtTinhTrang;
    private javax.swing.JLabel txtTinhTrang1;
    // End of variables declaration//GEN-END:variables
}
