/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Message;
import Controller.services;
import javax.swing.JTable;
import javax.swing.table.*;
import java.sql.*;
import java.util.Collections;
import javax.swing.ImageIcon;
import Models.*;

/**
 *
 * @author ADMIN
 */
public class PanelManageAccount extends javax.swing.JPanel {
    private String idRemove = "-1";
    /**
     * Creates new form ManageAccount
     */
    public void loadUser()
    {
        DefaultTableModel model = (DefaultTableModel)table_account.getModel();
        model.setNumRows(0);
        ((People_QuanLy)services.user).loadUser(model);
    }
    public PanelManageAccount() {
        initComponents();
        loadUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_account = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtboxGioitinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtboxNgaySinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtboxDiachi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtboxSdt = new javax.swing.JTextField();
        txtboxhoTen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtboxCMND = new javax.swing.JTextField();
        txtboxID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAddAccount = new javax.swing.JButton();
        btnRemoveAccount = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtboxChucVu = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1420, 748));

        table_account.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        table_account.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "Password", "Admin", "Ban"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_account.setToolTipText("");
        table_account.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_accountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_account);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Giới tính");

        txtboxGioitinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ngày sinh");

        txtboxNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtboxNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtboxNgaySinhActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Địa chỉ");

        txtboxDiachi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("SĐT");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Họ tên");

        txtboxSdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtboxhoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("CMND");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("User ID");

        txtboxCMND.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtboxID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Thông tin cá nhân");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_reset-password.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_update-info.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("*");

        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setText("*");

        jLabel11.setForeground(new java.awt.Color(255, 51, 0));
        jLabel11.setText("*");

        jLabel12.setText("yyyy-mm-dd");

        btnAddAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_add-account.png"))); // NOI18N
        btnAddAccount.setBorderPainted(false);
        btnAddAccount.setContentAreaFilled(false);
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });

        btnRemoveAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_remove-account.png"))); // NOI18N
        btnRemoveAccount.setBorderPainted(false);
        btnRemoveAccount.setContentAreaFilled(false);
        btnRemoveAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAccountActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_refresh.png"))); // NOI18N
        btnRefresh.setBorderPainted(false);
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Chức vụ");

        txtboxChucVu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnRemoveAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(txtboxID, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtboxhoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtboxGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtboxDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtboxSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel12))
                                        .addComponent(txtboxNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtboxCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtboxChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel13))
                        .addGap(203, 203, 203))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoveAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtboxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtboxhoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtboxGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtboxNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtboxDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtboxSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtboxCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtboxChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtboxNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtboxNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxNgaySinhActionPerformed

    private void table_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_accountMouseClicked
            int row = table_account.rowAtPoint( evt.getPoint() );
            int column = table_account.columnAtPoint( evt.getPoint() );
            String id = table_account.getModel().getValueAt(row, 0)+"";
            this.idRemove = id;
            People_User user = new People_User();
            try {
                Statement stmt = services.cnn.con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM `user` WHERE user_id='"+id+"'");
                if(rs.next())
                user = new People_User(rs);
            }
            catch(Exception e)
            {
                services.msgbox("Error", "Có lỗi trong quá trình lấy dữ liệu ID "+id);
                services.msg(e);
                return;
            }
            txtboxhoTen.setText(user.getTen());
            txtboxID.setText(user.getID());
            txtboxGioitinh.setText(user.getGioitinh());
            txtboxDiachi.setText(user.getDiachi());
            txtboxCMND.setText(user.getCMND());
            txtboxNgaySinh.setText(String.valueOf(user.getNgaysinh()));
            txtboxSdt.setText(user.getSdt());
            txtboxChucVu.setText(user.getChucvu());
            if(column==3) // Admin
            {
                Boolean isAdmin = (boolean)table_account.getModel().getValueAt(row, column);
                {
                    try{
                        Statement stmt = services.cnn.con.createStatement();
                        if(isAdmin) stmt.execute("UPDATE `login` SET `isAdmin`='1' WHERE user_id='"+id+"'");
                        else stmt.execute("UPDATE `login` SET `isAdmin`='0' WHERE user_id='"+id+"'");
                    }
                    catch(Exception e)
                    {
                        services.msgbox("Error","Không thể cấp quyền admin ! Có lỗi xảy ra .");
                        services.msg(e);
                    }
                }
                services.msg("Admin function");
            }
            if(column==4) // Ban
            {
                Boolean isBan = (boolean)table_account.getModel().getValueAt(row, column);
                {
                    try{
                        Statement stmt = services.cnn.con.createStatement();
                        if(isBan) stmt.execute("UPDATE `login` SET `banned`='1' WHERE user_id='"+id+"'");
                        else stmt.execute("UPDATE `login` SET `banned`='0' WHERE user_id='"+id+"'");
                    }
                    catch(Exception e)
                    {
                        services.msgbox("Error","Không thể unban/ban ! Có lỗi xảy ra .");
                        services.msg(e);
                    }
                }
                services.msg("Ban function");
            }
            //services.msg("Table clicked");        // TODO add your handling code here:
    }//GEN-LAST:event_table_accountMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(txtboxhoTen.getText().compareTo("")==0||txtboxID.getText().compareTo("")==0||txtboxCMND.getText().compareTo("")==0)
        {
            services.msgbox("Error", "Vui lòng điền đẩy đủ thông tin bắt buộc");
            return;
        }
        try{
            Statement stmt = services.cnn.con.createStatement();
            stmt.execute("UPDATE `login` SET `user_id`='"+txtboxID.getText()+"' WHERE `user_id`='"+this.idRemove+"'");
            stmt.execute("UPDATE `user` SET `user_id`='"+txtboxID.getText()+"',`Ten`='"+txtboxhoTen.getText()+"',`Gioi tinh`='"+txtboxGioitinh.getText()+"',`Ngay sinh`='"+txtboxNgaySinh.getText()+"',`Dia chi`='"+txtboxDiachi.getText()+"',`Sdt`='"+txtboxSdt.getText()+"',`CMND`='"+txtboxCMND.getText()+"',`chucvu`='"+txtboxChucVu.getText()+"' WHERE user_id='"+this.idRemove+"'");
            services.msgbox("Success", "Cập nhật thông tin thành công");
        }
        catch(Exception e)
        {
            services.msgbox("Error","Có lỗi trong quá trình cập nhật thông tin ID "+txtboxID.getText());
            services.msg(e);
            return;
        }
        services.msg("Update info clicked");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        // TODO add your handling code here:
        //Add account
        FrameAddAccount add = new FrameAddAccount();
        add.show();
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void btnRemoveAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAccountActionPerformed
        // TODO add your handling code here:
        //Remove Account
        if(Integer.parseInt(this.idRemove)==-1)
        {
            return;
        }
        try{
            Statement stmt = services.cnn.con.createStatement();
            stmt.execute("DELETE FROM `user` WHERE user_id='"+this.idRemove+"'");
            stmt.execute("DELETE FROM `login` WHERE user_id='"+this.idRemove+"'");
            services.msgbox("Success", "Xóa user thành công!");
            services.sendLog(services.user.getID(),services.user.getTen(),"removeuser",Message.removeUser+this.idRemove);
            loadUser();
        }
        catch(Exception e)
        {
            services.msgbox("Error","Có lỗi trong quá trình xóa tài khoản này");
            services.msg(e);
        }
    }//GEN-LAST:event_btnRemoveAccountActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadUser();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrameResetPass fr = new FrameResetPass();
        fr.show();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_account;
    private javax.swing.JTextField txtboxCMND;
    private javax.swing.JTextField txtboxChucVu;
    private javax.swing.JTextField txtboxDiachi;
    private javax.swing.JTextField txtboxGioitinh;
    private javax.swing.JTextField txtboxID;
    private javax.swing.JTextField txtboxNgaySinh;
    private javax.swing.JTextField txtboxSdt;
    private javax.swing.JTextField txtboxhoTen;
    // End of variables declaration//GEN-END:variables
}
