/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Message;
import Controller.services;
import java.sql.ResultSet;
import Models.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class PanelBook extends javax.swing.JPanel {
    private Model_Sach book = new Model_Sach();
    private DefaultTableModel model ;
    private int starRate = 5;
    private boolean rated = false;
    /**
     * Creates new form PanelBook
     */
    private void loadComment()
    {
        boolean isUser = false;
        if(services.user instanceof People_Khach)
        {
            isUser = true;
            for(Model_Sach sach:((People_Khach)services.user).getInventory("inventory"))
            {
                if(sach.getID().compareTo(txtID.getText().split(":")[1].trim())==0)
                {
                    btnSubmitRate.setEnabled(true);
                    break;
                }
            }
        }
        float rate = 0;
        int count = 0;
        this.model.setNumRows(0);
        try{
            String sql = "SELECT * FROM `rate` WHERE `book_id`='"+txtID.getText().split(":")[1].trim()+"'";
            ResultSet rs = services.cnn.con.createStatement().executeQuery(sql);
            while(rs.next())
            {
                if(isUser && !rated && rs.getString("user").compareTo(services.user.getID())==0) this.rated = true;
                this.model.addRow(new Object[]{rs.getDate("time"), services.cnn.getRowInDB("user", "user_id", rs.getString("user")).getString("Ten"),rs.getString("comment"),rs.getInt("star")});
                rate += rs.getInt("star");
                count +=1;
            }
            if(count!=0)
            labelGeneralStar.setText(String.format("%.1f",(float)rate/count));
            else labelGeneralStar.setText("0");
            if(this.rated)
            {
                txtRate.setText("Bạn đã để lại đánh giá sách này.");
                txtRate.setEditable(false);
                btnSubmitRate.setEnabled(false);
            }
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }
    public PanelBook(Model_Sach book) {
        initComponents();
        if(services.user instanceof People_NhanVien || services.user instanceof People_QuanLy) // Nhan Vien
        {
            btnAddToCart.setEnabled(false);
            btnBuy.setEnabled(false);
            btnSubmitRate.setEnabled(false);
            txtRate.setEnabled(false);
        }
        this.model = (DefaultTableModel) this.tableRate.getModel();      
        tableRate.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableRate.getColumnModel().getColumn(1).setPreferredWidth(138);
        tableRate.getColumnModel().getColumn(2).setPreferredWidth(626);
        tableRate.getColumnModel().getColumn(3).setPreferredWidth(63);
        try
        {
            txtID.setText(txtID.getText()+book.getID());
            txtTen.setText(book.getTen());
            txtGia.setText(txtGia.getText()+book.getGia());
            txtSoLuong.setText(txtSoLuong.getText()+book.getSoLuong());
            txtTheLoai.setText(txtTheLoai.getText()+services.cnn.getRowInDB("danhmuc", "id", book.getTheLoai()).getString("ten"));
            txtTacGia.setText(txtTacGia.getText()+services.cnn.getRowInDB("user", "user_id", book.getIdTacGia()).getString("Ten"));
            services.setImgLabel(bookImage, services.getUrlImageBook(book.getImage()),200, 300);
            if(book.getSoLuong()<=0)
            {
                services.setImgButton(btnBuy, services.getUrlImageComp("button_buy_disable.png"));
                btnBuy.setEnabled(false);
                btnAddToCart.setVisible(false);
            }   
            
            this.loadComment();
        }
        catch(Exception e)
        {
            services.msgbox("Error", "Có lỗi trong quá trình lấy sách");
            services.msg(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JLabel();
        txtTheLoai = new javax.swing.JLabel();
        txtGia = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRate = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRate = new javax.swing.JTextArea();
        btnSubmitRate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelGeneralStar = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1420, 748));

        bookImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bookImage.setMaximumSize(new java.awt.Dimension(32767, 32767));
        bookImage.setMinimumSize(new java.awt.Dimension(300, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin sách");

        txtID.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtID.setText("ID : ");

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtTacGia.setText("Tác giả : ");

        txtTheLoai.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtTheLoai.setText("Thể loại : ");

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtGia.setText("Giá : ");

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSoLuong.setText("Số lượng : ");

        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_buy.png"))); // NOI18N
        btnBuy.setBorderPainted(false);
        btnBuy.setContentAreaFilled(false);
        btnBuy.setFocusable(false);
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        btnAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_add-to-cart.png"))); // NOI18N
        btnAddToCart.setBorderPainted(false);
        btnAddToCart.setContentAreaFilled(false);
        btnAddToCart.setFocusable(false);
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        tableRate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tableRate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày đánh giá ", "Người dùng ", "Nhận xét", "Đánh giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRate);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Đánh giá");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Để lại đánh giá");

        txtRate.setColumns(20);
        txtRate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRate.setRows(5);
        jScrollPane2.setViewportView(txtRate);

        btnSubmitRate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_okmsg.png"))); // NOI18N
        btnSubmitRate.setBorderPainted(false);
        btnSubmitRate.setContentAreaFilled(false);
        btnSubmitRate.setEnabled(false);
        btnSubmitRate.setFocusable(false);
        btnSubmitRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRateActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star.png"))); // NOI18N

        labelGeneralStar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelGeneralStar.setText("1");

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star_full.png"))); // NOI18N
        star1.setFocusable(false);
        star1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star1MousePressed(evt);
            }
        });

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star_full.png"))); // NOI18N
        star2.setFocusable(false);
        star2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star2MousePressed(evt);
            }
        });

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star_full.png"))); // NOI18N
        star3.setFocusable(false);
        star3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star3MousePressed(evt);
            }
        });

        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star_full.png"))); // NOI18N
        star4.setFocusable(false);
        star4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star4MousePressed(evt);
            }
        });

        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star_full.png"))); // NOI18N
        star5.setFocusable(false);
        star5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star5MousePressed(evt);
            }
        });

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTen.setText("Ten");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(94, 94, 94)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelGeneralStar)
                .addGap(219, 219, 219))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmitRate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(star1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(star2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(star3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(star4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(star5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(bookImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGia)
                                    .addComponent(txtSoLuong)
                                    .addComponent(txtID)
                                    .addComponent(txtTacGia)
                                    .addComponent(txtTen)
                                    .addComponent(txtTheLoai)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelGeneralStar)
                                .addComponent(jLabel5)))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID)
                                .addGap(18, 18, 18)
                                .addComponent(txtTen)
                                .addGap(18, 18, 18)
                                .addComponent(txtTacGia)
                                .addGap(18, 18, 18)
                                .addComponent(txtTheLoai)
                                .addGap(18, 18, 18)
                                .addComponent(txtGia)
                                .addGap(26, 26, 26)
                                .addComponent(txtSoLuong)
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bookImage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(star1)
                            .addComponent(star2)
                            .addComponent(star3)
                            .addComponent(star4)
                            .addComponent(star5))
                        .addGap(17, 17, 17)
                        .addComponent(btnSubmitRate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        services.msg("btn add to cart click");
        Model_Sach book = services.getBookByID(txtID.getText().split(":")[1].trim());
        if(book==null)
        {
            return;
        }
        ((People_Khach)services.user).addBookToCart(txtID.getText().split(":")[1].trim());
        ((People_Khach)services.user).updateInventory("cart");
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        if(!(services.user instanceof People_Khach))
        {
            return;
        }
        if(txtID.getText().compareTo("")==0) return;
        Model_Sach book = services.getBookByID(txtID.getText().split(":")[1].trim());
        if(book==null){
            services.msg("Book null");
            return;
        }
        book.setSoLuong(1);
        if(services.user.getSoDu()>=book.getGia())
        {
            ((People_Khach)services.user).buyBook(book.getGia());
            boolean isExist = false;
            for(Model_Sach item :((People_Khach)services.user).getInventory("inventory"))
            {
                if(book.getID().compareTo(item.getID())==0)
                {
                    item.setSoLuong(item.getSoLuong()+1);
                    isExist = true;
                    break;
                }
            }
            if(!isExist) ((People_Khach)services.user).getInventory("inventory").add(book);
            ((People_Khach)services.user).updateInventory("cart");
            ((People_Khach)services.user).updateInventory("inventory");
            services.buyBook(book.getID(), 1);
            txtSoLuong.setText("Số lượng : "+(Integer.parseInt(txtSoLuong.getText().split(":")[1].trim())-1));
            if(Integer.parseInt(txtSoLuong.getText().split(":")[1].trim())==0)
            {
                btnBuy.setEnabled(false);
                btnAddToCart.setEnabled(false);
            }
            services.msgbox("Success","Mua sach thanh cong");
            this.loadComment();
            services.sendLog(services.user.getID(),services.user.getTen(),"buy", Message.buyBook +book.getID());
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    private void star1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseClicked
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 1;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(empty));
        star3.setIcon(new ImageIcon(empty));
        star4.setIcon(new ImageIcon(empty));
        star5.setIcon(new ImageIcon(empty));
    }//GEN-LAST:event_star1MouseClicked

    private void star2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseClicked
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 2;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(full));
        star3.setIcon(new ImageIcon(empty));
        star4.setIcon(new ImageIcon(empty));
        star5.setIcon(new ImageIcon(empty));
    }//GEN-LAST:event_star2MouseClicked

    private void star3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseClicked
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 3;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(full));
        star3.setIcon(new ImageIcon(full));
        star4.setIcon(new ImageIcon(empty));
        star5.setIcon(new ImageIcon(empty));
    }//GEN-LAST:event_star3MouseClicked

    private void star4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseClicked
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 4;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(full));
        star3.setIcon(new ImageIcon(full));
        star4.setIcon(new ImageIcon(full));
        star5.setIcon(new ImageIcon(empty));
    }//GEN-LAST:event_star4MouseClicked

    private void star5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseClicked
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 5;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(full));
        star3.setIcon(new ImageIcon(full));
        star4.setIcon(new ImageIcon(full));
        star5.setIcon(new ImageIcon(full));
    }//GEN-LAST:event_star5MouseClicked

    private void star1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MousePressed
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 1;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(empty));
        star3.setIcon(new ImageIcon(empty));
        star4.setIcon(new ImageIcon(empty));
        star5.setIcon(new ImageIcon(empty)); 
    }//GEN-LAST:event_star1MousePressed

    private void star2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MousePressed
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 2;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(full));
        star3.setIcon(new ImageIcon(empty));
        star4.setIcon(new ImageIcon(empty));
        star5.setIcon(new ImageIcon(empty));
    }//GEN-LAST:event_star2MousePressed

    private void star3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MousePressed
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 3;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(full));
        star3.setIcon(new ImageIcon(full));
        star4.setIcon(new ImageIcon(empty));
        star5.setIcon(new ImageIcon(empty));
    }//GEN-LAST:event_star3MousePressed

    private void star4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MousePressed
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 4;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(full));
        star3.setIcon(new ImageIcon(full));
        star4.setIcon(new ImageIcon(full));
        star5.setIcon(new ImageIcon(empty));
    }//GEN-LAST:event_star4MousePressed

    private void star5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MousePressed
        // TODO add your handling code here:
        if(this.rated) return;
        this.starRate = 5;
        String full = "./src/assets/star_full.png";
        String empty = "./src/assets/star_empty.png";
        star1.setIcon(new ImageIcon(full));
        star2.setIcon(new ImageIcon(full));
        star3.setIcon(new ImageIcon(full));
        star4.setIcon(new ImageIcon(full));
        star5.setIcon(new ImageIcon(full));
    }//GEN-LAST:event_star5MousePressed

    private void btnSubmitRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRateActionPerformed
        // TODO add your handling code here:
        if(!(services.user instanceof People_Khach))
        {
            return;
        }
        ((People_Khach)services.user).submitRate(txtID.getText().split(":")[1].trim(),txtRate.getText(),this.starRate);
        this.loadComment();
    }//GEN-LAST:event_btnSubmitRateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookImage;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnSubmitRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelGeneralStar;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    private javax.swing.JTable tableRate;
    private javax.swing.JLabel txtGia;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextArea txtRate;
    private javax.swing.JLabel txtSoLuong;
    private javax.swing.JLabel txtTacGia;
    private javax.swing.JLabel txtTen;
    private javax.swing.JLabel txtTheLoai;
    // End of variables declaration//GEN-END:variables
}
