/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.services;
import Models.Model_Sach;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.WIDTH;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import Models.*;
/**
 *
 * @author ADMIN
 */
public class PanelInventory extends javax.swing.JPanel {
    private String last_id;
    private DefaultTableModel model;
    /**
     * Creates new form PanelCart
     */
    public PanelInventory() {
        initComponents();
        model = (DefaultTableModel) tableListSach.getModel();
        this.loadCartUser();
        txtID.setEditable(false);
        txtTen.setEditable(false);
        txtTacGia.setEditable(false);
        txtTheLoai.setEditable(false);
        txtGia.setEditable(false);
    }
    public void loadCartUser()
    {
        try{
            String sql = "SELECT * FROM `inventory` WHERE user_id='"+services.user.getID()+"'";
            ResultSet rs = services.cnn.con.createStatement().executeQuery(sql);
            if(rs.next())
            {        
                if(services.user instanceof People_Khach)
                {
                    //services.msg("Load cart in menu");
                    ((People_Khach)services.user).loadInventory(rs, "inventory");
                }
            }
            for(Model_Sach sach : ((People_Khach)services.user).getInventory("inventory"))
            {
                //services.msg("Add row : "+sach.getTen());
                model.addRow(new Object[]{sach.getID(), sach.getTen(), services.cnn.getRowInDB("danhmuc", "id", sach.getTheLoai().trim()).getString("ten"), sach.getSoLuong()});
            }
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }
    public void loadBook(String id)
    {
     Model_Sach sach = services.getBookByID(id);   
     if(sach==null) return;
        {
            try{
                txtID.setText(sach.getID());
                txtTacGia.setText(services.cnn.getRowInDB("user", "user_id", sach.getIdTacGia()).getString("Ten"));
                txtTen.setText(sach.getTen());
                txtTheLoai.setText(services.cnn.getRowInDB("danhmuc", "id", sach.getTheLoai().trim()).getString("ten"));
                txtGia.setText(sach.getGia()+"");

                BufferedImage img = ImageIO.read(new URL(services.getUrlImageBook(sach.getImage())));
                ImageIcon icon = new ImageIcon(img.getScaledInstance(150, 200, WIDTH));
                imageBook.setIcon(icon);
                }
            catch(Exception e)
            {
                services.msgbox("Error","Không thể lấy thông tin sách");
                services.msg(e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTheLoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JLabel();
        imageBook = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListSach = new javax.swing.JTable();
        txtGia = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1420, 748));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Kho sách cá nhân");

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTen.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tên");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tác giả");

        txtTheLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTheLoai.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thể loại");

        txtThanhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtThanhTien.setText("Giá");

        imageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/demo.jpg"))); // NOI18N
        imageBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_view.png"))); // NOI18N
        btnView.setBorder(null);
        btnView.setBorderPainted(false);
        btnView.setContentAreaFilled(false);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        txtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtID.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ID");

        tableListSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableListSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID sách", "Tên sách", "Thể loại", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableListSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListSachMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableListSachMousePressed(evt);
            }
        });
        tableListSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableListSachKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableListSachKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableListSach);

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGia.setBorder(null);

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTacGia.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(imageBook)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(txtThanhTien))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtThanhTien)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageBook)))
                        .addGap(65, 65, 65)
                        .addComponent(btnView)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        if(txtID.getText().compareTo("")==0)
        {
            return;
        }
        services.disposeParent(this, new PanelBook(services.getBookByID(txtID.getText().trim())));
    }//GEN-LAST:event_btnViewActionPerformed

    private void tableListSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListSachMouseClicked
        // TODO add your handling code here:
        int row = tableListSach.getSelectedRow();
        this.last_id = (String)tableListSach.getValueAt(row, 0);
        this.loadBook((String)tableListSach.getValueAt(row, 0));
    }//GEN-LAST:event_tableListSachMouseClicked

    private void tableListSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableListSachKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tableListSachKeyPressed

    private void tableListSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableListSachKeyReleased
        // TODO add your handling code here:
        int row = tableListSach.getSelectedRow();
        this.last_id = (String)tableListSach.getValueAt(row, 0);
        this.loadBook((String)tableListSach.getValueAt(row, 0));
    }//GEN-LAST:event_tableListSachKeyReleased

    private void tableListSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListSachMousePressed
        // TODO add your handling code here:
        int row = tableListSach.getSelectedRow();
        this.last_id = (String)tableListSach.getValueAt(row, 0);
        this.loadBook((String)tableListSach.getValueAt(row, 0));
    }//GEN-LAST:event_tableListSachMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JLabel imageBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListSach;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTen;
    private javax.swing.JLabel txtThanhTien;
    private javax.swing.JTextField txtTheLoai;
    // End of variables declaration//GEN-END:variables
}
