/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.util.Date;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.List;
import java.util.ArrayList;
import Controller.services;
import Models.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class PanelManageLogs extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelManageLogs
     */
    private class Log
    {
        protected String user,action;
        protected Date time;
    }
    private List<Log> logs = new ArrayList<Log>();
    private DefaultTableModel model ;
    public PanelManageLogs() {
        initComponents();
        model = (DefaultTableModel) tableLogs.getModel();
        String sqlGetLogs = "" ;
        if(services.user instanceof People_QuanLy)
        {
            services.msg("Log manager");
        }
        else if(services.user instanceof People_NhanVien){
            services.msg("Log staff");   
        }
        else if(services.user instanceof People_Khach)
        {
            labelMessage.setText("Lịch sử mua hàng");
            services.msg("Log customer "+services.user.getID().trim());
        }
        loadLogs(sqlGetLogs);
    }
    private void loadLogs(String sqlGetLogs)
    {
        model.setRowCount(0);
        for(Model_Log tmp : services.user.viewLogs())
        {
            model.addRow(new Object[]{ tmp.getTime().toString(), tmp.getUser(), tmp.getAction()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLogs = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1420, 748));

        labelMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMessage.setText("Quản lý nhật ký");

        tableLogs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "User", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableLogs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(labelMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JTable tableLogs;
    // End of variables declaration//GEN-END:variables
}
