/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Message;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import Controller.services;
import Models.Model_Sach;
import java.awt.CardLayout;
import javax.swing.JFrame;
import java.util.ArrayList;
import java.sql.*;
/**
 *
 * @author ADMIN
 */
public class PanelLibrary extends javax.swing.JPanel {
    //Static filter
    protected static int minPrice = 0;
    protected static int maxPrice = 0;
    
    //Variable
    /**
     * Creates new form PanelLibrary
     */
    public PanelLibrary() {
        initComponents();    
        loadShelfBook();
        panelBook1.setBorder(null);
        panelBook2.setBorder(null);
        try{
            String sqlCategory = "SELECT `ten` FROM `danhmuc` WHERE 1";
            Statement stmt = services.cnn.con.createStatement();
            ResultSet rs = stmt.executeQuery(sqlCategory);
            while(rs.next())
            {
                comboboxFilter.addItem(rs.getString("ten"));
            }
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }
    private void loadShelfBook()
    {
        ArrayList<Model_Sach> mostView = new ArrayList<Model_Sach>();
        ArrayList<Model_Sach> mostBuy = new ArrayList<Model_Sach>();
        try{
            String sqlMostView = "SELECT * FROM `khosach` WHERE 1 ORDER BY `luotxem` DESC LIMIT 50";
            Statement stmt = services.cnn.con.createStatement();
            ResultSet rs = stmt.executeQuery(sqlMostView);
            while(rs.next())
            {
                mostView.add(new Model_Sach(rs));
            }
            String sqlMostBuy = "SELECT * FROM `khosach` WHERE 1 ORDER BY `luotmua` DESC LIMIT 50";
            rs = stmt.executeQuery(sqlMostBuy);
            while(rs.next())
            {
                mostBuy.add(new Model_Sach(rs));
            }
            labelBook1.setText("Sách xem nhiều");
            services.changePanel(panelBook1, new PanelShelfBook(mostView), 1237, 225);
            
            labelBook2.setText("Sách mua nhiều");
            services.changePanel(panelBook2, new PanelShelfBook(mostBuy), 1237, 225);
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelBook1 = new javax.swing.JLabel();
        panelBook1 = new javax.swing.JPanel();
        labelBook2 = new javax.swing.JLabel();
        panelBook2 = new javax.swing.JPanel();
        btnFind = new javax.swing.JButton();
        txtKeyWord = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboboxFilter = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(1420, 748));
        setPreferredSize(new java.awt.Dimension(1420, 748));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thư viện");

        labelBook1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelBook1.setText("Label Shelf Book 1");

        panelBook1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBook1.setMinimumSize(new java.awt.Dimension(1237, 225));
        panelBook1.setPreferredSize(new java.awt.Dimension(1237, 225));

        javax.swing.GroupLayout panelBook1Layout = new javax.swing.GroupLayout(panelBook1);
        panelBook1.setLayout(panelBook1Layout);
        panelBook1Layout.setHorizontalGroup(
            panelBook1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1235, Short.MAX_VALUE)
        );
        panelBook1Layout.setVerticalGroup(
            panelBook1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        labelBook2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelBook2.setText("Label Shelf Book 2");

        panelBook2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBook2.setMinimumSize(new java.awt.Dimension(1237, 225));

        javax.swing.GroupLayout panelBook2Layout = new javax.swing.GroupLayout(panelBook2);
        panelBook2.setLayout(panelBook2Layout);
        panelBook2Layout.setHorizontalGroup(
            panelBook2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1235, Short.MAX_VALUE)
        );
        panelBook2Layout.setVerticalGroup(
            panelBook2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_search.png"))); // NOI18N
        btnFind.setBorder(null);
        btnFind.setContentAreaFilled(false);
        btnFind.setFocusPainted(false);
        btnFind.setFocusable(false);
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        txtKeyWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tìm sách");

        comboboxFilter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboboxFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phân loại", "Theo ID", "Theo tên" }));
        comboboxFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxFilterItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboboxFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKeyWord, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBook1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBook1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelBook2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBook2))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboboxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBook1)
                .addGap(33, 33, 33)
                .addComponent(panelBook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelBook2)
                .addGap(30, 30, 30)
                .addComponent(panelBook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        if(((String)comboboxFilter.getSelectedItem()).compareTo("Phân loại")==0)
        {
            services.msgbox("Thông báo",Message.chooseFilter);
            return;
        }
        ArrayList<Model_Sach> results = new ArrayList<Model_Sach>();
        if(((String)comboboxFilter.getSelectedItem()).compareTo("Theo ID")==0)
        {
            try{
                String sql = "SELECT * FROM `khosach` WHERE `book_id`='"+txtKeyWord.getText().trim()+"'";
                Statement stmt = services.cnn.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                while(rs.next())
                {
                    Model_Sach tmp =  new Model_Sach(rs);
                    results.add(tmp);
                }
            }
            catch(Exception e)
            {
                services.msg(e);
            }
        }
        else{
            try{
            String sql = "SELECT * FROM `khosach` WHERE 1";
            Statement stmt = services.cnn.con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                Model_Sach tmp =  new Model_Sach(rs);
                if(tmp.getTen().toLowerCase().contains(txtKeyWord.getText().trim().toLowerCase()))
                results.add(tmp);
            }
            }
            catch(Exception e)
            {
                services.msg(e);
            }
        }
        if(results.size()>0)
                    services.changePanel(this, new PanelResult(results), 1420, 748);
        else
            services.msgbox("Error", Message.notFoundResultBook);
    }//GEN-LAST:event_btnFindActionPerformed

    private void comboboxFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxFilterItemStateChanged
        // TODO add your handling code here:
        String value = (String)comboboxFilter.getSelectedItem();
        if(value.compareTo("Theo ID")==0||value.compareTo("Phân loại")==0||value.compareTo("Theo tên")==0)
        {
            return;
        }
        try{
            ArrayList<Model_Sach> list = new ArrayList<Model_Sach>();
            String sql = "SELECT * FROM `khosach` WHERE `theloai` = '"+services.cnn.getRowInDB("danhmuc", "ten", value).getString("id")+"'";
            ResultSet rs = services.cnn.con.createStatement().executeQuery(sql);
            while(rs.next())
            {
                list.add(new Model_Sach(rs));
            }
            services.changePanel(this, new PanelResult(list), 1420, 748);
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }//GEN-LAST:event_comboboxFilterItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> comboboxFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBook1;
    private javax.swing.JLabel labelBook2;
    private javax.swing.JPanel panelBook1;
    private javax.swing.JPanel panelBook2;
    private javax.swing.JTextField txtKeyWord;
    // End of variables declaration//GEN-END:variables
}
