/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Message;
import Controller.services;
import Models.Model_Sach;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.WIDTH;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import Models.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class PanelCart extends javax.swing.JPanel {
    private String last_id;
    private DefaultTableModel model;
    /**
     * Creates new form PanelCart
     */
    public PanelCart() {
        initComponents();
        model = (DefaultTableModel) tableListSach.getModel();
        this.loadCartUser();
        txtID.setEditable(false);
        txtTen.setEditable(false);
        txtSL.setEditable(false);
        txtTacGia.setEditable(false);
        txtTheLoai.setEditable(false);
        txtGia.setEditable(false);
    }
    public void getSetItem()
    {
        int row = tableListSach.getSelectedRow();
        this.last_id = (String)tableListSach.getValueAt(row, 0);
        this.loadBook((String)tableListSach.getValueAt(row, 0));
    }
    public void clearItem()
    {
        txtID.setText("");
        txtTacGia.setText("");
        txtTen.setText("");
        txtTheLoai.setText("");
        txtGia.setText("");
        txtSL.setText("");
        services.setImgLabel(imageBook, services.getUrlImageBook("demo.jpg"), 150, 200);
    }
    public void loadCartUser()
    {
        model.setNumRows(0);
        try{
            String sql = "SELECT * FROM `inventory` WHERE user_id='"+services.user.getID()+"'";
            ResultSet rs = services.cnn.con.createStatement().executeQuery(sql);
            if(rs.next())
            {        
                if(services.user instanceof People_Khach)
                {
                    //services.msg("Load cart in menu");
                    ((People_Khach)services.user).loadInventory(rs, "cart");
                }
            }
            for(Model_Sach sach : ((People_Khach)services.user).getInventory("cart"))
            {
                //services.msg("Add row : "+sach.getTen());
                model.addRow(new Object[]{sach.getID(), sach.getTen(), services.cnn.getRowInDB("danhmuc", "id", sach.getTheLoai().trim()).getString("ten"), sach.getSoLuong()});
            }
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }
    public void loadBook(String id)
    {
     Model_Sach sach = services.getBookByID(id);   
     if(sach==null) return;
        {
            try{
                txtID.setText(sach.getID());
                txtTacGia.setText(services.cnn.getRowInDB("user", "user_id", sach.getIdTacGia()).getString("Ten"));
                txtTen.setText(sach.getTen());
                txtTheLoai.setText(services.cnn.getRowInDB("danhmuc", "id", sach.getTheLoai().trim()).getString("ten"));
                txtGia.setText(sach.getGia()+"");
                txtSL.setText(sach.getSoLuong()+"");

                BufferedImage img = ImageIO.read(new URL(services.getUrlImageBook(sach.getImage())));
                ImageIcon icon = new ImageIcon(img.getScaledInstance(150, 200, WIDTH));
                imageBook.setIcon(icon);
                }
            catch(Exception e)
            {
                services.msgbox("Error","Không thể lấy thông tin sách");
                services.msg(e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTheLoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JLabel();
        imageBook = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListSach = new javax.swing.JTable();
        txtSL = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1420, 748));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Giỏ hàng");

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTen.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tên");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tác giả");

        txtTheLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTheLoai.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thể loại");

        txtThanhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtThanhTien.setText("Giá");

        imageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/demo.jpg"))); // NOI18N
        imageBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTinhTrang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTinhTrang.setText("SL");

        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_buy.png"))); // NOI18N
        btnBuy.setBorder(null);
        btnBuy.setBorderPainted(false);
        btnBuy.setContentAreaFilled(false);
        btnBuy.setFocusable(false);
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        txtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtID.setBorder(null);

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button_remove.png"))); // NOI18N
        btnRemove.setBorder(null);
        btnRemove.setBorderPainted(false);
        btnRemove.setContentAreaFilled(false);
        btnRemove.setFocusable(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ID");

        tableListSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableListSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID sách", "Tên sách", "Thể loại", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableListSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListSachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableListSachMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableListSachMousePressed(evt);
            }
        });
        tableListSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableListSachKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableListSachKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableListSach);

        txtSL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSL.setBorder(null);

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGia.setBorder(null);

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTacGia.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(imageBook)
                        .addGap(105, 105, 105)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTinhTrang)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(txtThanhTien))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(913, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(imageBook)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemove)
                            .addComponent(btnBuy))
                        .addGap(34, 34, 34)))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel7)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtThanhTien)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTinhTrang)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(382, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        if(!(services.user instanceof People_Khach))
        {
            return;
        }
        if(txtID.getText().compareTo("")==0) return;
        try{
            for(Model_Sach sach:((People_Khach)services.user).getInventory("cart"))
            {
                if(sach.getID().compareTo(txtID.getText())==0)
                {
                    if(services.user.getSoDu()>=sach.getGia()*sach.getSoLuong())
                    {
                        ((People_Khach)services.user).buyBook(sach.getGia()*sach.getSoLuong());
                        boolean isExist = false;
                        for(Model_Sach item :((People_Khach)services.user).getInventory("inventory"))
                        {
                            if(sach.getID().compareTo(item.getID())==0)
                            {
                                item.setSoLuong(item.getSoLuong()+sach.getSoLuong());
                                isExist = true;
                                break;
                            }
                        }
                        if(!isExist) ((People_Khach)services.user).getInventory("inventory").add(sach);
                        ((People_Khach)services.user).getInventory("cart").remove(sach);
                        ((People_Khach)services.user).updateInventory("cart");
                        ((People_Khach)services.user).updateInventory("inventory");
                        this.loadCartUser();
                        this.clearItem();
                        services.msgbox("Success","Mua sach thanh cong");
                        services.buyBook(sach.getID(), sach.getSoLuong());
                        txtSL.setText((Integer.parseInt(txtSL.getText())-sach.getSoLuong())+"");
                        services.sendLog(services.user.getID(),services.user.getTen(),"buy", Message.buyBook +sach.getID());
                        break;
                    }
                    else return ;
                }
            }
        }
        catch(Exception e)
        {
            services.msg(e);
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
        if(txtID.getText().compareTo("")==0) return;
        {
            try{
                for(Model_Sach item:((People_Khach)services.user).getInventory("cart"))
                {
                    if(item.getID().compareTo(txtID.getText())==0)
                    {
                        ((People_Khach)services.user).getInventory("cart").remove(item);
                        break;
                    }
            }
            ((People_Khach)services.user).updateInventory("cart");
            this.loadCartUser();
            this.clearItem();
            }
            catch(Exception e)
            {
                services.msg("Panel Cart");
                services.msg(e);
            }
        }   
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tableListSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListSachMouseClicked
        // TODO add your handling code here:
        //getSetItem();
    }//GEN-LAST:event_tableListSachMouseClicked

    private void tableListSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableListSachKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableListSachKeyPressed

    private void tableListSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableListSachKeyReleased
        // TODO add your handling code here:
        getSetItem();
    }//GEN-LAST:event_tableListSachKeyReleased

    private void tableListSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListSachMouseEntered
        // TODO add your handling code here:
        //getSetItem();
    }//GEN-LAST:event_tableListSachMouseEntered

    private void tableListSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListSachMousePressed
        // TODO add your handling code here:
        getSetItem();
    }//GEN-LAST:event_tableListSachMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel imageBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListSach;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTen;
    private javax.swing.JLabel txtThanhTien;
    private javax.swing.JTextField txtTheLoai;
    private javax.swing.JLabel txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
